name: Keep the versions up-to-date

on:
  release:
    types: [published, edited]

jobs:
  run-tag-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Actions-R-Us/actions-tagger@latest
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          publish_latest_tag: 'true'
